import type { Metadata } from "next";
import "./globals.css";
import theme from "@/theme/themeConfig";
import { ConfigProvider } from "antd";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import MainLayout from "@/components/layout/MainLayout";
import { Footer, Navbar } from "@/components/common";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const locale = await getLocale();
  // const messages = await getMessages();

  const locale = "th";
  return (
    <html lang={locale}>
      <body className="w-full">
        {/* <NextIntlClientProvider messages={'messages'}> */}
        <ConfigProvider theme={theme}>
          <div className="w-full relative">
            <header className="w-full sticky top-0 p-0 z-[99]">
              <Navbar />
            </header>
            <MainLayout className="w-full1">{children}</MainLayout>
            <Footer className="w-full" />
          </div>
        </ConfigProvider>
        {/* </NextIntlClientProvider> */}
      </body>
    </html>
  );
}
